# Generated by Django 4.2 on 2023-04-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0002_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
