# Generated by Django 4.2 on 2023-05-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0003_guide_latitude_guide_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourismo.guide')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('platitude', models.FloatField()),
                ('plongitude', models.FloatField()),
                ('dlatitude', models.FloatField()),
                ('dlongitude', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('budget_type', models.CharField(choices=[('negotiation', 'Negotiation'), ('NRP', 'Nepalese Rupees'), ('USD', 'US Dollars')], default='negotiation', max_length=20)),
                ('budget_cash', models.PositiveIntegerField(blank=True, null=True)),
                ('guide_requests', models.ManyToManyField(related_name='plan_requests', through='tourismo.GuideRequest', to='tourismo.guide')),
                ('guides', models.ManyToManyField(related_name='plans', to='tourismo.guide')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourismo.tourist')),
            ],
        ),
        migrations.AddField(
            model_name='guiderequest',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourismo.plan'),
        ),
    ]
