# Generated by Django 4.2 on 2023-05-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0006_guide_user_tourist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='user',
        ),
    ]
