# Generated by Django 4.2 on 2023-05-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0007_remove_guide_user_remove_tourist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='budget_cash',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
    ]
