# Generated by Django 4.2 on 2023-05-06 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0010_alter_plan_budget_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.DateTimeField()),
            ],
        ),
    ]
