# Generated by Django 4.2 on 2023-05-06 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0011_touristnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristnotification',
            name='tourist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourismo.tourist'),
        ),
    ]
