# Generated by Django 4.2 on 2023-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0012_touristnotification_tourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristnotification',
            name='tourist',
            field=models.IntegerField(null=True),
        ),
    ]
