# Generated by Django 4.2 on 2023-05-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0014_touristrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristrequest',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourismo.guide'),
        ),
    ]
