# Generated by Django 4.2 on 2023-05-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0015_touristrequest_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristrequest',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
