# Generated by Django 4.2 on 2023-05-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0017_guidenotification_remove_touristrequest_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_intro', models.FileField(null=True, upload_to='hotel_videos/')),
                ('room_size', models.CharField(max_length=100)),
                ('room_prices_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('room_details', models.TextField()),
                ('room_image1', models.ImageField(upload_to='room_images/')),
                ('room_image2', models.ImageField(upload_to='room_images/')),
                ('room_image3', models.ImageField(upload_to='room_images/')),
                ('tour_package_image1', models.ImageField(upload_to='tour_package_images/')),
                ('tour_package_image2', models.ImageField(upload_to='tour_package_images/')),
                ('food_and_drink_image1', models.ImageField(upload_to='food_and_drink_images/')),
                ('food_and_drink_image2', models.ImageField(upload_to='food_and_drink_images/')),
                ('food_and_drink_image3', models.ImageField(upload_to='food_and_drink_images/')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourismo.guide')),
            ],
        ),
    ]
