# Generated by Django 4.2 on 2023-05-24 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0018_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='food_and_drink_image1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_and_drink_image2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_and_drink_image3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_image1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_image2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room_image3',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tour_package_image1',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tour_package_image2',
        ),
        migrations.CreateModel(
            name='TourPackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_package_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_package_images', to='tourismo.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='tourismo.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='FoodAndDrinkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_and_drink_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_and_drink_images', to='tourismo.hotel')),
            ],
        ),
    ]
