# Generated by Django 4.2 on 2023-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0019_remove_hotel_food_and_drink_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='budget_cash',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dcoordinate',
        ),
        migrations.AddField(
            model_name='plan',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
