# Generated by Django 4.2 on 2023-06-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0020_remove_plan_budget_cash_remove_plan_budget_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiderequest',
            name='quantity_order',
            field=models.IntegerField(null=True),
        ),
    ]
