# Generated by Django 4.2 on 2023-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0021_guiderequest_quantity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='remaining_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
