# Generated by Django 4.2 on 2023-06-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismo', '0023_alter_plan_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='remaining_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
